name: Roundcube
version: b5ecd02
slug: roundcube
description: Roundcube webmail client
url: https://github.com/erik73/hassio-addons
arch:
- aarch64
- amd64
- armv7
init: false
ingress: true
panel_icon: mdi:email
map:
- ssl
services:
- mysql:need
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: Roundcube
hassio_api: true
options:
  domain_name: mydomain.no-ip.com
schema:
  domain_name: str
image: ghcr.io/erik73/roundcube/{arch}
