---
channel: edge
addons:
  steve:
    repository: erik73/app-steve
    target: steve
    image: ghcr.io/erik73/steve/{arch}
  mailserver:
    repository: erik73/app-mail
    target: mail
    image: ghcr.io/erik73/mailserver/{arch}
  mailfilter:
    repository: erik73/app-mailfilter
    target: mailfilter
    image: ghcr.io/erik73/mailfilter/{arch}
  tellsticklive:
    repository: erik73/app-tellsticklive
    target: tellsticklive
    image: ghcr.io/erik73/tellsticklive/{arch}
  mariadb:
    repository: erik73/app-mariadb
    target: mariadb
    image: ghcr.io/erik73/mariadb/{arch}
  phpmyadmin:
    repository: erik73/app-phpmyadmin
    target: phpmyadmin
    image: ghcr.io/erik73/phpmyadmin/{arch}
  roundcube:
    repository: erik73/app-roundcube
    target: roundcube
    image: ghcr.io/erik73/roundcube/{arch}
  influxdb2:
    repository: erik73/app-influxdb2
    target: influxdb2
    image: ghcr.io/erik73/influxdb2/{arch}
