name: InfluxDB3 Explorer
version: e58f6d7
slug: influxdb3-explorer
description: Example app by Home Assistant Community Apps
url: https://github.com/hassio-addons/app-example
init: false
arch:
- aarch64
- amd64
webui: http://[HOST]:[PORT:80]
ports:
  80/tcp: 8888
ports_description:
  80/tcp: InfluxDB3 Explorer
options:
  log_level: info
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
image: ghcr.io/erik73/influxdb3-explorer/{arch}
